#!/bin/bash -xe

. common-config

APACHE_IP=`juju run -m ${CONTROLLER}:${MODEL} --unit apache2/0 'unit-get private-address'`

function bootstrap() {
	juju switch ${CONTROLLER}
	local image_metadata_url="http://${APACHE_IP}/openstack-images/"
	./generate-juju-config
	set +e
	juju controllers | grep -q vpil-openstack-controller
	found=$?
	set -e
	if [ $found == 0 ];
	then
		juju kill-controller --yes vpil-openstack-controller
		juju unregister --yes vpil-openstack-controller
	fi
	juju add-cloud --replace vpil-openstack openstack-cloud.yaml
	juju add-credential --replace -f openstack-credentials.yaml vpil-openstack
        local net_id=`nova net-list | grep internal | awk {'print $2'}`
	juju bootstrap vpil-openstack-controller vpil-openstack \
		--keep-broken --upload-tools \
		--config image-metadata-url=$image_metadata_url \
		--config network=${net_id} \
		--config use-floating-ip=true
}

bootstrap
