#!/bin/bash

. novarc

sudo apt-get install apache2
sudo rm -rf /var/www/html/openstack-images

export IMAGE_ID=`glance image-list | grep xenial | awk {'print $2'}`
rm -rf ./images
mkdir images
juju metadata generate-image -r RegionKVM -u $OS_AUTH_URL -d images -i $IMAGE_ID
sudo cp -R images/images /var/www/html/openstack-images
sudo chmod -R 755 /var/www/html/openstack-images

eth_ip=`ifconfig eth0 | grep "inet addr" | cut -d ':' -f 2 | cut -d ' ' -f 1`

image_metadata_url="http://${eth_ip}/openstack-images/"

envsubst < openstack-cloud.yaml.tmpl > openstack-cloud.yaml
juju add-cloud --replace vpil-openstack openstack-cloud.yaml
juju add-credential --replace -f openstack-credentials.yaml vpil-openstack
juju bootstrap vpil-openstack-controller vpil-openstack --upload-tools --config image-metadata-url=$image_metadata_url
