#!/bin/bash -xe

if [ $# -ne 0 ];
then
	echo "syntax: $0"
	exit 1
fi

. common-config
. novarc

LOCAL_IMAGES_DIR=./images
APACHE_IP=`juju run -m ${CONTROLLER}:${MODEL} --unit apache2/0 'unit-get private-address'`

sudo apt-get install apache2
BLEH=<<END
sudo rm -rf $APACHE_IMAGES_DIR

rm -rf $LOCAL_IMAGES_DIR
mkdir $LOCAL_IMAGES_DIR
export IMAGE_ID=`glance image-list | grep xenial | grep qcow2 | awk {'print $2'}`
juju metadata generate-image -r RegionOne -u $OS_AUTH_URL -d $LOCAL_IMAGES_DIR -i $IMAGE_ID --virt-type="kvm"
export IMAGE_ID=`glance image-list | grep xenial | grep root-tar | awk {'print $2'}`
juju metadata generate-image -r RegionOne -u $OS_AUTH_URL -d $LOCAL_IMAGES_DIR -i $IMAGE_ID --virt-type="lxd"
END

IMAGE_METADATA_URL="http://${APACHE_IP}/openstack-images/"
envsubst < openstack-cloud.yaml.tmpl > openstack-cloud.yaml
