#!/bin/bash

if [ $# -ne 2 ];
then
	echo "syntax: $0 <kvm|lxd> <1|2>"
	exit 1
fi

. novarc

HYPERVISOR=$1
JUJU_VERSION=$2
REGION=Region${HYPERVISOR^^}
LOCAL_IMAGES_DIR=./${HYPERVISOR}-images
APACHE_IMAGES_DIR=/var/www/html/openstack-images-$HYPERVISOR

sudo apt-get install apache2
sudo rm -rf $APACHE_IMAGES_DIR

IMAGE_URL="http://`juju run --unit glance-region-${HYPERVISOR}/0 'unit-get private-address'`:9292"

export XENIAL_IMAGE_ID=`glance --os-image-url=$IMAGE_URL image-list | grep xenial | awk {'print $2'}`
export TRUSTY_IMAGE_ID=`glance --os-image-url=$IMAGE_URL image-list | grep trusty | awk {'print $2'}`
rm -rf $LOCAL_IMAGES_DIR
mkdir $LOCAL_IMAGES_DIR
juju metadata generate-image -r $REGION -u $OS_AUTH_URL -d $LOCAL_IMAGES_DIR -i $XENIAL_IMAGE_ID -s xenial
juju metadata generate-image -r $REGION -u $OS_AUTH_URL -d $LOCAL_IMAGES_DIR -i $TRUSTY_IMAGE_ID -s trusty
sudo cp -R $LOCAL_IMAGES_DIR/images $APACHE_IMAGES_DIR
sudo chmod -R 755 $APACHE_IMAGES_DIR

ETH_IP=`ifconfig eth0 | grep "inet addr" | cut -d ':' -f 2 | cut -d ' ' -f 1`
IMAGE_METADATA_URL="http://${ETH_IP}/openstack-images-${HYPERVISOR}/"

if [ $JUJU_VERSION == 2 ]
then
	HYPERVISOR=$HYPERVISOR REGION=$REGION envsubst < openstack-cloud.yaml.tmpl > openstack-cloud-${HYPERVISOR}.yaml
else
	HYPERVISOR=$HYPERVISOR IMAGE_METADATA_URL=$IMAGE_METADATA_URL REGION=$REGION envsubst < juju-openstack-env.yaml.part.tmpl > juju-openstack-env-$HYPERVISOR.yaml.part	
fi
