#!/bin/bash

if [ $# -ne 2 ];
then
	echo "syntax: $0 <kvm|lxd> <1|2>"
fi

. novarc

HYPERVISOR=$1
JUJU_VERSION=$2
REGION=Region${HYPERVISOR^^}
LOCAL_IMAGES_DIR=./${HYPERVISOR}-images
APACHE_IMAGES_DIR=/var/www/html/openstack-images-$HYPERVISOR

sudo apt-get install apache2
sudo rm -rf $APACHE_IMAGES_DIR

IMAGE_URL="http://`juju run --unit glance-region-${HYPERVISOR}/0 'unit-get private-address'`:9292"

export IMAGE_ID=`glance --os-image-url=$IMAGE_URL image-list | grep xenial | awk {'print $2'}`
rm -rf $LOCAL_IMAGES_DIR
mkdir $LOCAL_IMAGES_DIR
juju metadata generate-image -r $REGION -u $OS_AUTH_URL -d $LOCAL_IMAGES_DIR -i $IMAGE_ID
sudo cp -R $LOCAL_IMAGES_DIR/images $APACHE_IMAGES_DIR
sudo chmod -R 755 $APACHE_IMAGES_DIR

ETH_IP=`ifconfig eth0 | grep "inet addr" | cut -d ':' -f 2 | cut -d ' ' -f 1`

IMAGE_METADATA_URL="http://${ETH_IP}/openstack-images-${HYPERVISOR}/"


if [ $JUJU_VERSION == 2 ]
then
	envsubst < openstack-cloud.yaml.tmpl > openstack-cloud.yaml
	juju kill-controller --yes vpil-openstack-controller
	juju unregister vpil-openstack-controller
	juju add-cloud --replace vpil-openstack openstack-cloud.yaml
	juju add-credential --replace -f openstack-credentials.yaml vpil-openstack
	juju bootstrap vpil-openstack-controller vpil-openstack --upload-tools --config image-metadata-url=$IMAGE_METADATA_URL
else
	OS_AUTH_URL=$OS_AUTH_URL HYPERVISOR=$HYPERVISOR IMAGE_METADATA_URL=$IMAGE_METADATA_URL REGION=$REGION envsubst < juju-openstack-env.yaml.part.tmpl > juju-openstack-env-$HYPERVISOR.yaml.part	
fi
