#!/bin/bash -x
sudo apt-get install python-glanceclient python-novaclient \
	python-keystoneclient python-neutronclient

. novarc

./setup-images
./setup-networks

OS_REGION_NAME=RegionKVM nova keypair-add mykey-kvm > ~/.ssh/id_rsa_cloud.kvm
OS_REGION_NAME=RegionLXD nova keypair-add mykey-lxd > ~/.ssh/id_rsa_cloud.lxd
chmod 700 ~/.ssh/id_rsa_cloud.kvm ~/.ssh/id_rsa_cloud.lxd
