#!/bin/bash -x
sudo apt-get install python-glanceclient python-novaclient \
	python-keystoneclient python-neutronclient

. novarc

./setup-quotas
./setup-images
./setup-networks

nova keypair-add mykey > ~/.ssh/id_rsa_cloud
chmod 700 ~/.ssh/id_rsa_cloud
