#!/bin/bash -x
. novarc

function setup_region_networking {
	local region=$1
	local network=$2
	local gateway=$3
	local dns=$4
	local allocation_pool=$5

	neutron --os-region=$region net-create flat-provider-network --provider:network_type flat --provider:physical_network physnet1
	neutron --os-region-name=$region subnet-create --name flat-provider-subnet --gateway $gateway --dns-nameserver $dns --allocation-pool $allocation_pool flat-provider-network $network
}

setup_region_networking RegionLXD 10.246.64.0/21 10.246.64.1 10.246.64.1 "start=10.246.70.1,end=10.246.70.100"
setup_region_networking RegionKVM 10.246.64.0/21 10.246.64.1 10.246.64.1 "start=10.246.70.101,end=10.246.70.200"

juju ssh neutron-gateway-region-lxd/0 "sudo sh -c 'echo \"enable_isolated_metadata = True\" >> /etc/neutron/dhcp_agent.ini && service neutron-dhcp-agent restart'"
juju ssh neutron-gateway-region-kvm/0 "sudo sh -c 'echo \"enable_isolated_metadata = True\" >> /etc/neutron/dhcp_agent.ini && service neutron-dhcp-agent restart'"
